// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzvDIcH5SQDvhhBQOAdRJQILaBmDW4IzU',
    appId: '1:596082230745:web:488fab7da96b754cb785c8',
    messagingSenderId: '596082230745',
    projectId: 'unimarket-18f7f',
    authDomain: 'unimarket-18f7f.firebaseapp.com',
    storageBucket: 'unimarket-18f7f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMWLYza0hY5B_hxSX7y892AQk1pEKD2Xs',
    appId: '1:596082230745:android:96cd037919b2aeb2b785c8',
    messagingSenderId: '596082230745',
    projectId: 'unimarket-18f7f',
    storageBucket: 'unimarket-18f7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0lk4iEc11aU5emM43gACN1XjuC9hFWEA',
    appId: '1:596082230745:ios:dbcf823f20aba803b785c8',
    messagingSenderId: '596082230745',
    projectId: 'unimarket-18f7f',
    storageBucket: 'unimarket-18f7f.firebasestorage.app',
    iosBundleId: 'com.example.uniMarketplace',
  );
}
